# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/grpc/messaging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/grpc/messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/grpc/messaging.proto\x12\x04grpc\"D\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"E\n\x0fMessageResponse\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2N\n\x10MessagingService\x12:\n\x0bSendMessage\x12\x14.grpc.MessageRequest\x1a\x15.grpc.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=34
  _globals['_MESSAGEREQUEST']._serialized_end=102
  _globals['_MESSAGERESPONSE']._serialized_start=104
  _globals['_MESSAGERESPONSE']._serialized_end=173
  _globals['_MESSAGINGSERVICE']._serialized_start=175
  _globals['_MESSAGINGSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
